---
# Prep SCCM Install-------------------------------------------------------------------
- name: Prep SCCM Install
  ansible.builtin.include_role:
    name: ludus_sccm_prep_siteserver

# Start SCCM Install-------------------------------------------------------------------
- name: Begin SCCM Install
  ansible.builtin.include_tasks:
    file: install_sccm.yml

# Start CM Account Configuration-------------------------------------------------------
- name: Begin CM Account Configuration
  ansible.builtin.include_tasks:
    file: cm_accounts.yml

# Start NAA Configuration--------------------------------------------------------------
- name: Begin NAA Configuration
  ansible.builtin.include_tasks:
    file: config_naa.yml
  when: ludus_sccm_configure_naa

# Configure Push Account---------------------------------------------------------------
- name: Configure Push Client Installation
  ansible.builtin.include_tasks:
    file: client_push.yml
  when: ludus_sccm_configure_client_push

# Configure Discovery Methods----------------------------------------------------------
- name: Configure Discovery Methods
  ansible.builtin.include_tasks:
    file: discovery_methods.yml

# Configure PXE------------------------------------------------------------------------
- name: Configure PXE
  ansible.builtin.include_tasks:
    file: config_pxe.yaml
  when: ludus_sccm_enable_pxe
