---
dependencies: []

galaxy_info:
  role_name: add_accounts_to_admins
  author: Chris Thompson
  description: Add arbitrary accounts to local admins
  company: SpecterOps
  license: GPLv3
  min_ansible_version: "2.10"
  platforms:
    - name: Windows

  galaxy_tags:
    - windows
    - security
    - sccm
    - activedirectory
    - server
    - ludus
