###########################
## Network Configuration ##
###########################

# 10.X.0.0/16 is the network containing all servers and clients

# 10.X.10.0/24: Central Administration Site (CAS), Domain Controllers (DC), and Miscellaneous Systems
#   10.X.10.10: attacker
#   10.X.10.50: cas-pss
#   10.X.10.51: cas-db
#   10.X.10.57: cas-scp
#   10.X.10.100: dc

# 10.X.11.0/24: Primary Site One (PS1)
#   10.X.11.50: ps1-pss
#   10.X.11.51: ps1-db
#   10.X.11.52: ps1-psv
#   10.X.11.53: ps1-lib
#   10.X.11.54: ps1-sms
#   10.X.11.55: ps1-mp
#   10.X.11.56: ps1-dp
#   10.X.11.10: ps1-dev
#   10.X.11.200: ps1-sec

# 10.X.12.0/24: Primary Site Two (PS2)
#   10.X.12.50: ps2-pss

# All devices will become clients of SCCM site PS1 via automatic client push installation


######################################
## Domain and Miscellaneous Servers ##
######################################

  # DC: Domain Controller
ludus:
  - vm_name: "{{ range_id }}-dc"
    hostname: "dc"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 10
    ip_last_octet: 100
    ram_gb: 4
    ram_min_gb: 1
    cpus: 2
    windows:
      chocolatey_packages:
        - procmon
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: primary-dc
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.install_adcs


#######################################
## Central Administration Site (CAS) ##
#######################################

  # CAS-DB: Site Database Server
  - vm_name: "{{ range_id }}-cas-db"
    hostname: "cas-db"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 10
    ip_last_octet: 51
    ram_gb: 6
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - name: synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for CAS-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-cas-pss"
            role: synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.install_site_database
    role_vars:
      ludus_sccm_site_server_hostname: 'cas-pss'
      ludus_sccm_sql_server_hostname: 'cas-db'    
      ludus_sccm_sql_additional_sysadmin_accounts: 'MAYYHEM\domainadmin'

  # CAS-SCP: Service Connection Point
  - vm_name: "{{ range_id }}-cas-scp"
    hostname: "cas-scp"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 10
    ip_last_octet: 57
    ram_gb: 4
    ram_min_gb: 1
    cpus: 2
    windows:
      chocolatey_packages:
        - procmon
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for CAS-PSS to be online before adding to local admins and creating content share
        depends_on:
          - vm_name: "{{ range_id }}-cas-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: 'cas-pss'

  # CAS-PSS: Primary Site Server
  - vm_name: "{{ range_id }}-cas-pss"
    hostname: "cas-pss" 
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 10
    ip_last_octet: 50
    ram_gb: 6
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_siteserver
      - name: synzack.ludus_sccm.install_primary_site
        # Wait for SQL and SCP to be online before installing CAS
        depends_on:
          - vm_name: "{{ range_id }}-cas-db"
            role: synzack.ludus_sccm.install_site_database
          - vm_name: "{{ range_id }}-cas-scp"
            role: synzack.ludus_sccm.add_pss_to_admins
          # Wait for PS1 to be installed to extend hierarchy to CAS
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.install_primary_site
    role_vars:
      ludus_sccm_sitecode: CAS
      ludus_sccm_sitename: Central Administration Site
      ludus_sccm_child_site_server_hostname: 'ps1-pss.mayyhem.com'
      ludus_sccm_win_sccm_config_default_template: ExtendPrimaryToCAS.ini.j2
      ludus_sccm_site_server_hostname: 'cas-pss'
      ludus_sccm_sql_server_hostname: 'cas-db'
      ludus_sccm_scp_hostname: 'cas-scp'
      # Settings that should only be configured in primary sites
      ludus_sccm_configure_client_push: false
      ludus_sccm_enable_pxe: false
      ludus_sccm_configure_naa: false
      ludus_sccm_configure_task_sequence: false
      ludus_sccm_configure_domain_join: false
      ludus_sccm_enable_active_directory_forest_discovery: false
      ludus_sccm_enable_active_directory_boundary_creation: false
      ludus_sccm_enable_subnet_boundary_creation: false
      ludus_sccm_enable_active_directory_group_discovery: false
      ludus_sccm_enable_active_directory_system_discovery: false
      ludus_sccm_enable_active_directory_user_discovery: false


############################
## Primary Site One (PS1) ##
############################

  # PS1-DB: Site Database Server
  - vm_name: "{{ range_id }}-ps1-db"
    hostname: "ps1-db"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 51
    ram_gb: 6
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.install_site_database
    role_vars:
      ludus_sccm_site_server_hostname: 'ps1-pss'
      ludus_sccm_sql_server_hostname: 'ps1-db'
      ludus_sccm_sql_additional_sysadmin_accounts: 'MAYYHEM\domainadmin'

  # PS1-LIB: Content Library Server
  - vm_name: "{{ range_id }}-ps1-lib"
    hostname: "ps1-lib"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 53
    ram_gb: 4
    ram_min_gb: 1
    cpus: 2
    windows:
      chocolatey_packages:
        - procmon
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins and creating content share
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.create_contentlib_share
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: 'ps1-pss'

  # PS1-PSV: Passive Site Server
  - vm_name: "{{ range_id }}-ps1-psv"
    hostname: "ps1-psv"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 52
    ram_gb: 4
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.install_site_database
      - synzack.ludus_sccm.prep_siteserver
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_is_primary_or_cas: false
      ludus_sccm_sitecode: PS1
      ludus_sccm_site_server_hostname: 'ps1-pss'
      ludus_sccm_sql_server_hostname: 'ps1-psv'
      ludus_sccm_sql_additional_sysadmin_accounts: 'MAYYHEM\domainadmin'

  # PS1-DP: Distribution Point
  - vm_name: "{{ range_id }}-ps1-dp"
    hostname: "ps1-dp"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 56
    ram_gb: 4
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_dp
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: 'ps1-pss'

  # PS1-MP: Management Point
  - vm_name: "{{ range_id }}-ps1-mp"
    hostname: "ps1-mp"
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 55
    ram_gb: 4
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_mp
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: "ps1-pss" 

  # PS1-SMS: SMS Provider
  - vm_name: "{{ range_id }}-ps1-sms"
    hostname: "ps1-sms" 
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 54
    ram_gb: 4
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - sysinternals
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_sms
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: 'ps1-pss'

    # PS1-PSS: Primary Site Server
  - vm_name: "{{ range_id }}-ps1-pss"
    hostname: "ps1-pss" 
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 50
    ram_gb: 6
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_siteserver
      - name: synzack.ludus_sccm.install_primary_site
        # Wait for the CAS and site systems to be online before installing site
        depends_on:
          - vm_name: "{{ range_id }}-ps1-db"
            role: synzack.ludus_sccm.install_site_database
          - vm_name: "{{ range_id }}-ps1-db"
            role: synzack.ludus_sccm.add_pss_to_admins
          - vm_name: "{{ range_id }}-ps1-sms"
            role: synzack.ludus_sccm.add_pss_to_admins
          - vm_name: "{{ range_id }}-ps1-dp"
            role: synzack.ludus_sccm.prep_dp
          - vm_name: "{{ range_id }}-ps1-dp"
            role: synzack.ludus_sccm.add_pss_to_admins
          - vm_name: "{{ range_id }}-ps1-mp"
            role: synzack.ludus_sccm.prep_mp
          - vm_name: "{{ range_id }}-ps1-mp"
            role: synzack.ludus_sccm.add_pss_to_admins
          - vm_name: "{{ range_id }}-ps1-dev"
            role: synzack.ludus_sccm.add_pss_to_admins
          - vm_name: "{{ range_id }}-ps1-sec"
            role: synzack.ludus_sccm.add_pss_to_admins
      - name: synzack.ludus_sccm.install_sms
        # Wait for SMS prep and site installation before installing remote SMS provider
        depends_on:
          - vm_name: "{{ range_id }}-ps1-sms"
            role: synzack.ludus_sccm.prep_sms
          - vm_name: "{{ range_id }}-ps1-sms"
            role: synzack.ludus_sccm.add_pss_to_admins
      - name: synzack.ludus_sccm.install_passive_site_server
        # Wait for content lib share, site database, and server prep to be done before installing passive site server
        depends_on:
          - vm_name: "{{ range_id }}-ps1-lib"
            role: synzack.ludus_sccm.create_contentlib_share
          - vm_name: "{{ range_id }}-ps1-psv"
            role: synzack.ludus_sccm.install_site_database
          - vm_name: "{{ range_id }}-ps1-psv"
            role: synzack.ludus_sccm.prep_siteserver        
          - vm_name: "{{ range_id }}-ps1-psv"
            role: synzack.ludus_sccm.add_pss_to_admins
      - name: synzack.ludus_sccm.install_secondary_site
        # Wait for secondary site server prep and site installation to be done before installing secondary site
        depends_on:
          - vm_name: "{{ range_id }}-ps1-sec"
            role: synzack.ludus_sccm.add_pss_to_admins
    role_vars:
      # This is a child site of CAS
      ludus_sccm_parent_sitecode: 'CAS'
      ludus_sccm_parent_site_server_hostname: 'cas-pss'
      ludus_sccm_add_accounts_to_admins: 'cas-pss$'
      ludus_sccm_win_sccm_config_default_template: ChildSiteConfigMgrSetup.ini.j2
      # Primary site specific settings (overrides defaults)
      ludus_sccm_sitecode: PS1
      ludus_sccm_sitename: Primary Site One
      ludus_sccm_site_server_hostname: 'ps1-pss'
      ludus_sccm_passive_hostname: 'ps1-psv'
      ludus_sccm_distro_server_hostname: 'ps1-dp'
      ludus_sccm_mgmt_server_hostname: 'ps1-mp'
      ludus_sccm_sql_server_hostname: 'ps1-db'
      ludus_sccm_sms_provider_hostname: 'ps1-sms'
      # Passive site specific settings
      ludus_sccm_contentlib_hostname: 'ps1-lib'
      # Secondary site specific settings
      ludus_sccm_secondary_sitecode: 'SEC'
      ludus_sccm_secondary_siteserver_fqdn: 'ps1-sec.mayyhem.com'

  # PS1-DEV: Development Workstation
  - vm_name: "{{ range_id }}-ps1-dev"
    hostname: "ps1-dev"
    template: win11-22h2-x64-enterprise-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 10
    ram_gb: 4
    ram_min_gb: 1
    cpus: 2
    windows:
      chocolatey_packages:
        - apimonitor
        - burp-suite-free-edition
        - openssh
        - procmon
        - systeminformer-nightlybuilds
        - visualstudio2022-remotetools
        - vscode
        - windows-sdk-10-version-2004-windbg
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-dev"
            role: synzack.ludus_sccm.windows_base
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      ludus_sccm_site_server_hostname: 'ps1-pss'

  # PS1-SEC: Secondary Site Server
  - vm_name: "{{ range_id }}-ps1-sec"
    hostname: "ps1-sec" 
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 11
    ip_last_octet: 200
    ram_gb: 6
    ram_min_gb: 1
    cpus: 2
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.ludus_sccm_prep_siteserver
      - name: synzack.ludus_sccm.add_pss_to_admins
        # Wait for PS1-PSS to be online before adding to local admins
        depends_on:
          - vm_name: "{{ range_id }}-ps1-pss"
            role: synzack.ludus_sccm.windows_base
    role_vars:
      # This is a secondary child site of PS1
      ludus_sccm_site_server_hostname: 'ps1-pss'

############################
## Primary Site Two (PS2) ##
############################

  # PS2-PSS: Standalone Primary Site Server
  - vm_name: "{{ range_id }}-ps2-pss"
    hostname: "ps2-pss" 
    template: win2022-server-x64-template
    testing:
      snapshot: true
      block_internet: false
    vlan: 12
    ip_last_octet: 50
    ram_gb: 6
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - procmon
        - sql-server-management-studio
        - systeminformer-nightlybuilds
        - wireshark
      sysprep: true
    domain:
      fqdn: mayyhem.com
      role: member
    roles:
      - synzack.ludus_sccm.windows_base
      - synzack.ludus_sccm.prep_siteserver
      - synzack.ludus_sccm.install_site_database
      - name: synzack.ludus_sccm.install_primary_site
        # Wait for the CAS and site database to be online before installing site
        depends_on:
          - vm_name: "{{ range_id }}-cas-pss"
            role: synzack.ludus_sccm.install_primary_site
    role_vars:
      # This is a standalone primary child site of CAS
      ludus_sccm_parent_sitecode: 'CAS'
      ludus_sccm_parent_site_server_hostname: 'cas-pss'
      ludus_sccm_win_sccm_config_default_template: ChildSiteConfigMgrSetup.ini.j2
      # Primary site specific settings (overrides defaults)
      ludus_sccm_sitecode: PS2
      ludus_sccm_sitename: Primary Site Two
      ludus_sccm_site_server_hostname: 'ps2-pss'
      ludus_sccm_sql_server_hostname: 'ps2-pss'
      ludus_sccm_configure_naa: false
      # Disable client push to prevent conflicts with PS1 site
      ludus_sccm_configure_client_push: false
      ludus_sccm_enable_pxe: false

notify:
  urls:
    - "ntfy://ntfy.sh/mayyhem-harbinger"