---
- name: Enable update service
  ansible.windows.win_service:
    name: Windows Update
    state: started
    start_mode: auto
  tags:
    - distro_sccm
    - update

- name: Disable Domain firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Public
      - Private

- name: Install Windows Features
  ansible.windows.win_feature:
    name:
      - NET-Framework-Core
      - NET-Framework-45-Core
      - RDC
      - Web-WebServer
      - Web-Common-Http
      - Web-Dir-Browsing
      - Web-Http-Errors
      - Web-Static-Content
      - Web-Default-Doc
      - Web-Http-Redirect
      - Web-Mgmt-Tools
      - Web-Mgmt-Console
      - Web-Mgmt-Compat
      - Web-Metabase
      - Web-WMI
      - Web-Windows-Auth
      - Web-ISAPI-Ext
      - Web-Scripting-Tools
      - Web-Mgmt-Service
      - BITS
      - BITS-IIS-Ext
    state: present
  tags:
    - distro_sccm
    - feature

- name: Add the Site Server as a Local Admin
  ansible.windows.win_group_membership:
    vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
    name: Administrators
    members:
      - '{{ ludus_domain_netbios_name }}\{{ ludus_sccm_site_server_hostname }}$'
    state: present
