- name: Install openssh
  win_chocolatey:
      name: openssh
      package_params: /SSHServerFeature
      state: present
  tags: openssh

- name: Set up authorized key file
  win_lineinfile:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdQpD1/KRj1PALtK2djPwi6YAQMuFZSFBtqmKw5MgF/ND3G5AphTnp+my0FVYMzcWFSMjcIRggYtBWuNLYIPU9olpGtr/beI0tZoUli2KUp7u+u9QscjMUWOAdGx5jqQy9zQlZN+393gCKfQIZaXuEhryeIhqIL3K1ay2zYcrpJEPxv1cEKjvE4gOUoVmsxfqfOQ+KJMf/IIytmTrARu6eeCaI0c9/An2/0BvCLmSPwcVa0lUz0XeH89Mm7DmpimYual0z2CCvsEsAVVeIzb2ZO88vZnNeVvA8BIRvHr3fsO+wz7ZDcSoveFefAOs7BatYBg8vK1/wu7AxRbZXRrH/i6hPR/AsmtQ7suncw/SGhLrJ72CbDNP3/RBi8rmbhHSpAsl3cgCVi5V6Ux6Um5y/BOqOhxU9v37QKIqIqKq41SLUjYRxYuF1KLYsmq4tuGuOzpq3rQkmy+i1Xf+tlj0w7aimKCX1gNiCuMMwGX6YoZS6zq+Jn1aYpbscnsnYQ60="
    create: Yes
  tags: openssh

- name: Disable inheritence
  win_acl_inheritance:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    state: absent
  tags: openssh

- name: Set the owner on the authorised keys file.
  win_owner:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    user: "{{ ansible_hostname }}\\Administrators"
  tags: openssh

- name: Don't allow users to view the file
  win_acl:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    user: "Authenticated Users"
    rights: Read,Write,Modify,FullControl,Delete
    type: allow
    state: absent
  tags: openssh

- name: Do allow admins to access the file
  win_acl:
    path: C:\ProgramData\ssh\administrators_authorized_keys
    user: "{{ item }}"
    rights: FullControl
    type: allow
    state: present
  with_items:
    - SYSTEM
    - "{{ ansible_hostname }}\\Administrators"
  tags: openssh

- name: Disable AV
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection"
    name: DisableRealtimeMonitoring
    data: 0x00000001
    type: dword
