---
- name: Enable update service
  ansible.windows.win_service:
    name: Windows Update
    state: started
    start_mode: auto

- name: Disable Domain firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
      - Domain
      - Public
      - Private

- name: Install .NET Windows Features
  ansible.windows.win_feature:
    name:
      - NET-Framework-Core
      - NET-Framework-45-Core
      - RSAT
      - Web-WebServer
      - Web-Mgmt-Console
      - Web-Metabase
      - Web-WMI
    state: present

- name: Add the Site Server as a Local Admin
  ansible.windows.win_group_membership:
    name: Administrators
    members:
      - '{{ ludus_domain_netbios_name }}\{{ ludus_sccm_site_server_hostname }}$'
    state: present

# Start SQL Server Install-------------------------------------------------------------------
- name: Begin SQL Server Install
  ansible.builtin.include_tasks:
    file: config_sql.yml
