---
- name: Check if the SQL Installation Files Exist
  win_stat:
    path: "C:\\enu_sql_server_2022_standard_edition_x64_dvd_43079f69.iso"
  register: file_stat

- name: Download SQL Server 2022 
  ansible.windows.win_get_url:
    url: "{{ sql2022_url }}"
    dest: C:\enu_sql_server_2022_standard_edition_x64_dvd_43079f69.iso
  when: not file_stat.stat.exists

- name: Mount SQL ISO
  community.windows.win_disk_image:
    image_path: C:\enu_sql_server_2022_standard_edition_x64_dvd_43079f69.iso
    state: present
  register: disk_image_out

- name: Create SQL Service Account
  microsoft.ad.user:
    name: '{{ SQLSVCACCOUNT }}'
    password: '{{ SQLSVCPASSWORD }}'
    state: present
    spn:
      set: 
      - 'MSSQLSvc/{{ SCCM_SQL_SERVER_HOSTNAME }}:1433'
      - 'MSSQLSvc/{{ SCCM_SQL_SERVER_HOSTNAME }}.{{ ludus_domain_fqdn }}:1433'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  
- name: Setup SQL Server
  ansible.windows.win_shell: |
    {{ disk_image_out.mount_paths[0] }}setup.exe /Q /IAcceptSQLServerLicenseTerms /ACTION="install" /FEATURES=SQL /INSTANCENAME=MSSQLSERVER /SQLSYSADMINACCOUNTS={{ SQLSYSADMINACCOUNTS }} /SQLSVCACCOUNT='{{ ludus_domain_netbios_name }}\{{ SQLSVCACCOUNT }}' /SQLSVCPASSWORD="{{ SQLSVCPASSWORD }}" /SQLMINMEMORY="8196" /SQLMAXMEMORY="16384"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  args:
    creates: "C:\\Program Files\\Microsoft SQL Server\\MSSQL16.MSSQLSERVER\\MSSQL\\Binn\\sqlservr.exe"

- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: C:\enu_sql_server_2022_standard_edition_x64_dvd_43079f69.iso
    state: absent