---
# Configure Passive Site Server----------------------------------------------------------------
- name: Install Windows Features
  ansible.windows.win_feature:
    name:
      - BITS
      - BITS-IIS-Ext
      - GPMC
      - NET-Framework-Core
      - NET-Framework-45-Core
      - RDC
      - RSAT
      - Web-WebServer
      - Web-Common-Http
      - Web-Dir-Browsing
      - Web-Http-Errors
      - Web-Static-Content
      - Web-Default-Doc
      - Web-Http-Redirect
      - Web-Mgmt-Tools
      - Web-Mgmt-Console
      - Web-Mgmt-Compat
      - Web-Metabase
      - Web-WMI
      - Web-Windows-Auth
      - Web-ISAPI-Ext
      - Web-Scripting-Tools
      - Web-Mgmt-Service
    state: present

- name: Create ContentLib directory
  ansible.windows.win_file:
    path: C:\ContentLib
    state: directory

- name: Add ContentLib share
  ansible.windows.win_share:
    name: ContentLib
    path: C:\ContentLib
    list: true
    full: '{{ ludus_domain_fqdn }}\Domain Users'
