---
#Configure Push Account----------------------------------------------------------------
- name: Create SCCM Push Account Domain Group
  microsoft.ad.group:
    name: sccm_push_accounts
    members:
      add:
      - '{{ PUSH_USERNAME }}'
    scope: global
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  

- name: Configure SCCM Client Push Installations
  autolabs.sccm.clientpush:
    name: '{{ ludus_domain_netbios_name }}\{{ PUSH_USERNAME }}'
    site_code: '{{ sitecode }}'
    EnableAutomaticClientPushInstallation: '{{ EnableAutomaticClientPushInstallation }}'
    EnableSystemTypeConfigurationManager: '{{ EnableSystemTypeConfigurationManager }}'
    EnableSystemTypeServer: '{{ EnableSystemTypeServer }}'
    EnableSystemTypeWorkstation: '{{ EnableSystemTypeWorkstation }}'
    InstallClientToDomainController: '{{ InstallClientToDomainController }}'
    AllownNTLMFallback: '{{ AllownNTLMFallback }}'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  

- name: Copy Push GPO Zip
  ansible.windows.win_copy:
    src: '{E38F225F-B020-4077-80ED-5195C3629651}.zip'
    dest: 'C:\{E38F225F-B020-4077-80ED-5195C3629651}.zip'
  

- name: Unzip Push GPO
  community.windows.win_unzip:
    src: 'C:\{E38F225F-B020-4077-80ED-5195C3629651}.zip'
    dest: C:\
    creates: 'C:\{E38F225F-B020-4077-80ED-5195C3629651}'
  

- name: Template Push Installation GPO Migration Table
  ansible.windows.win_template:
   src: "sccm_push.migtable.j2" 
   dest: C:\sccm_push.migtable
  

- name: Check if Group Policy Object exists
  win_shell: Get-GPO -Name "SCCM Push Account Local Admin"
  register: gpo_check
  ignore_errors: yes 
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"

- name: Create New Group Policy for Push Installation
  ansible.windows.win_shell: |
    New-GPO -Name "SCCM Push Account Local Admin" -Comment "Local Admin for SCCM Push Accounts"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: gpo_check.rc != 0

- name: Import Local Administrator Push Group Policy
  ansible.windows.win_shell: |
    Import-GPO -BackupGPOName "SCCM Push Account Local Admin" -TargetName "SCCM Push Account Local Admin" -path C:\ -MigrationTable C:\sccm_push.migtable
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: gpo_check.rc != 0

- name: Link Push GPO to Servers
  ansible.windows.win_shell: |
    New-GPLink -name "SCCM Push Account Local Admin" -Target "OU=Servers,DC=ludus,DC=domain" -Enforced Yes
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: EnableSystemTypeServer and gpo_check.rc != 0

- name: Link Push GPO to Workstations
  ansible.windows.win_shell: |
    New-GPLink -name "SCCM Push Account Local Admin" -Target "OU=Workstations,DC=ludus,DC=domain" -Enforced Yes
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: EnableSystemTypeWorkstation and gpo_check.rc != 0

- name: Link Push GPO to Domain Controllers
  ansible.windows.win_shell: |
    New-GPLink -name "SCCM Push Account Local Admin" -Target "OU=Workstations,DC=ludus,DC=domain" -Enforced Yes
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: InstallClientToDomainController and gpo_check.rc != 0

- name: Force gpupdate on OUs
  autolabs.sccm.force_gpupdate:
    workstations: '{{ EnableSystemTypeWorkstation }}'
    servers: '{{ EnableSystemTypeServer }}'
    domain_controllers: '{{ InstallClientToDomainController }}'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  