---
- name: Configure SCCM Discovery Methods
  autolabs.sccm.discovery_methods:
    site_code: '{{ sitecode }}'
    ActiveDirectoryForestDiscovery: '{{ ActiveDirectoryForestDiscovery }}'
    EnableActiveDirectorySiteBoundaryCreation: '{{ EnableActiveDirectorySiteBoundaryCreation }}'
    EnableSubnetBoundaryCreation: '{{ EnableSubnetBoundaryCreation }}'
    ActiveDirectoryGroupDiscovery: '{{ ActiveDirectoryGroupDiscovery }}'
    ActiveDirectorySystemDiscovery: '{{ ActiveDirectorySystemDiscovery }}'
    ActiveDirectoryUserDiscovery: '{{ ActiveDirectoryUserDiscovery }}'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"