---
ludus_install_directory: /opt/ludus
ludus_sccm_host_path: "C:\\ludus\\sccm"
ludus_sccm_sql_svc_account_username: 'sccmsqlsvc'
ludus_sccm_sql_svc_account_password: 'Password123'
#--------------------------Network Access Account--------------------------------
ludus_sccm_configure_naa: true
ludus_sccm_naa_username: 'networkaccess'
ludus_sccm_naa_password: 'Password123'
#--------------------------Client Push Account-----------------------------------------
ludus_sccm_configure_client_push: true
ludus_sccm_client_push_username: 'sccm_push'
ludus_sccm_client_push_password: 'password'
ludus_sccm_enable_automatic_client_push_installation: true
ludus_sccm_enable_system_type_configuration_manager: true
ludus_sccm_enable_system_type_server: true
ludus_sccm_enable_system_type_workstation: true
ludus_sccm_install_client_to_domain_controller: false
ludus_sccm_allow_NTLM_fallback: true
#--------------------------Task Sequence Account---------------------------------------
ludus_sccm_configure_task_sequence: true
ludus_sccm_task_sequence_username: 'sccm_push'
ludus_sccm_task_sequence_password: 'password'
#--------------------------Task Sequence - Domain Join Account-------------------------
ludus_sccm_configure_domain_join: true
ludus_sccm_domain_join_username: 'sccm_push'
ludus_sccm_domain_join_password: 'password'
#---------------------------Discovery Methods------------------------------------------
ludus_sccm_enable_active_directory_forest_discovery: true
ludus_sccm_enable_active_directory_boundary_creation: true
ludus_sccm_enable_subnet_boundary_creation: true
ludus_sccm_enable_active_directory_group_discovery: true
ludus_sccm_enable_active_directory_system_discovery: true
ludus_sccm_enable_active_directory_user_discovery: true
# ----------------------------------PXE-------------------------------------------------
ludus_sccm_enable_pxe: true
ludus_enable_pxe_password: false
ludus_pxe_password: 'Password123'
ludus_domain_join_account: domainjoin
ludus_domain_join_password: 'password'