---
- name: Install Windows Features
  ansible.windows.win_feature:
    name:
      - RDC
      - Web-Server
      - Web-ISAPI-Ext
      - Web-Windows-Auth
      - Web-Metabase
      - Web-WMI
      - WDS
      - WDS-Deployment
      - WDS-Transport
    state: present

- name: Check if WDS Server was already Initialized
  ansible.windows.win_reg_stat:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\WDSServer
  register: wds_registry_check
  
- name: Initialize WDS Server
  ansible.windows.win_shell: wdsutil /initialize-server /remInst:"C:\RemoteInstall"
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: not wds_registry_check.exists